name: Przykladowe workflow

on: 
  [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Konfiguracja
      run: echo "Plik skonfigurowano poprawnie"
    - name: Dodatkowy krok
      run: echo "Mozna wiec isc dalej"

