name: Action for merging

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  notify-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Get the name of the merged branch
        id: branch-name
        run: echo "::set-output name=branch::${{ github.head_ref }}"

      - name: Print merge message
        run: echo "Branch ${{ steps.branch-name.outputs.branch }} was merged with main branch."


        